baseURL = 'https://baishixi.blog/'
languageCode = 'en-us'
title = "BaiShiXi's Blog"
theme = 'hugo-simple'

[params]
  mainSections = ["posts"]

[[menu.main]]
name = "Posts"
pageRef = "/posts"
weight = 10

[markup.goldmark.renderer]
unsafe = true